# Generated by Django 3.2.7 on 2021-09-15 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='组名')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '通讯录组',
                'verbose_name_plural': '通讯录组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系人')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=8, verbose_name='性别')),
                ('mobile', models.IntegerField(blank=True, default=None, null=True, verbose_name='电话')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('appellative', models.CharField(blank=True, max_length=16, null=True, verbose_name='称呼')),
                ('qq', models.IntegerField(null=True, verbose_name='QQ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('units', models.CharField(blank=True, max_length=512, null=True, verbose_name='单位')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='家庭住址')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('gourp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_groups', to='users.groups')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['name'],
            },
        ),
    ]
