# Generated by Django 3.2.7 on 2021-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='电话'),
        ),
    ]
