# Generated by Django 3.2.7 on 2021-09-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commbook', '0003_alter_contacts_qq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='gourp',
        ),
    ]
