# Generated by Django 3.2.7 on 2021-09-22 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commbook', '0005_auto_20210922_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tacstsgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commbook.comgroup')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commbook.contacts')),
            ],
            options={
                'verbose_name': '分组关联',
                'ordering': ['-date_created'],
            },
        ),
    ]
