# Generated by Django 3.2.7 on 2021-09-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commbook', '0006_tacstsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacstsgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Comgroup', to='commbook.comgroup'),
        ),
        migrations.AlterField(
            model_name='tacstsgroup',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Contacts', to='commbook.contacts'),
        ),
    ]
