# Generated by Django 3.2.7 on 2021-09-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commbook', '0008_auto_20210923_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacstsgroup',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tacs_user', to='commbook.contacts'),
        ),
    ]
