# Generated by Django 3.2.7 on 2021-09-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commbook', '0009_alter_tacstsgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacstsgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tacs_group', to='commbook.comgroup'),
        ),
    ]
