# Generated by Django 3.2.7 on 2021-09-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='idcard',
        ),
    ]
