# Generated by Django 2.2.10 on 2021-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.IntegerField(blank=True, default=None, max_length=11, null=True, verbose_name='电话'),
        ),
    ]
