# Generated by Django 2.2.10 on 2021-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210911_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电话'),
        ),
    ]
