# Generated by Django 3.2.7 on 2021-09-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
