# Generated by Django 3.2.7 on 2021-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
