# Generated by Django 3.2.7 on 2021-09-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverifyrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱'),
        ),
    ]
