apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sdkreport
  annotations:
    kubernetes.io/change-cause: CHANGE_CAUSE
  namespace: consumer-prd
  labels:
    app: go-sdkreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sdkreport
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: go-sdkreport
    spec:
      nodeSelector:
        consumer: "true"
      containers:
      - name: go-sdkreport
        imagePullPolicy: Always
        image: registry-vpc.cn-shenzhen.aliyuncs.com/hll_elk/goconsumer:v1
        command: ["/opt/bin/goconsumer", "-c", "/opt/conf/Config-sdkreport.conf"]
#        resources:
#          limits:
#            cpu: "4"
#          requests:
#            cpu: "4"
        volumeMounts:
#          - name: test-volume
#            mountPath: /opt/logs
          - mountPath: /opt/conf/Config-sdkreport.conf
            name: go-sdkreport
            subPath: opt/conf/Config-sdkreport.conf
#      restartPolicy: Always
      volumes:
        - name: go-sdkreport
          configMap:
            name: go-sdkreport
            items:
               - key: Config-sdkreport.conf
                 path: opt/conf/Config-sdkreport.conf
#        - name: test-volume
#          hostPath:
#            path: /opt
